import { 
  BadgeDollarSign, 
  PiggyBank, 
  Wallet, 
  TrendingUp, 
  CreditCard, 
  Landmark, 
  Receipt, 
  Target, 
  ArrowUpCircle, 
  ArrowDownCircle, 
  Calculator, 
  ChartBar, 
  Coins, 
  DollarSign, 
  HandCoins, 
  Banknote, 
  CircleDollarSign, 
  LineChart, 
  WalletCards, 
  Percent 
} from "lucide-react"

export const userPreferenceOptions = {
  colors: {
    option1: {
      foreground: "text-blue-500",
      background: "bg-blue-100",
      text: "bg-blue-500 text-white",
    },
    option2: {
      foreground: "text-green-500",
      background: "bg-green-100",
      text: "bg-green-500 text-white",
    },
    option3: {
      foreground: "text-purple-500",
      background: "bg-purple-100",
      text: "bg-purple-500 text-white",
    },
    option4: {
      foreground: "text-indigo-500",
      background: "bg-indigo-100",
      text: "bg-indigo-500 text-white",
    },
    option5: {
      foreground: "text-pink-500",
      background: "bg-pink-100",
      text: "bg-pink-500 text-white",
    },
    option6: {
      foreground: "text-yellow-500",
      background: "bg-yellow-100",
      text: "bg-yellow-500 text-white",
    },
    option7: {
      foreground: "text-red-500",
      background: "bg-red-100",
      text: "bg-red-500 text-white",
    },
    option8: {
      foreground: "text-teal-500",
      background: "bg-teal-100",
      text: "bg-teal-500 text-white",
    },
    option9: {
      foreground: "text-cyan-500",
      background: "bg-cyan-100",
      text: "bg-cyan-500 text-white",
    },
    option10: {
      foreground: "text-emerald-500",
      background: "bg-emerald-100",
      text: "bg-emerald-500 text-white",
    },
    option11: {
      foreground: "text-lime-500",
      background: "bg-lime-100",
      text: "bg-lime-500 text-white",
    },
    option12: {
      foreground: "text-orange-500",
      background: "bg-orange-100",
      text: "bg-orange-500 text-white",
    },
    option13: {
      foreground: "text-amber-500",
      background: "bg-amber-100",
      text: "bg-amber-500 text-white",
    },
    option14: {
      foreground: "text-violet-500",
      background: "bg-violet-100",
      text: "bg-violet-500 text-white",
    },
    option15: {
      foreground: "text-fuchsia-500",
      background: "bg-fuchsia-100",
      text: "bg-fuchsia-500 text-white",
    },
    option16: {
      foreground: "text-rose-500",
      background: "bg-rose-100",
      text: "bg-rose-500 text-white",
    },
    option17: {
      foreground: "text-sky-500",
      background: "bg-sky-100",
      text: "bg-sky-500 text-white",
    },
    option18: {
      foreground: "text-slate-500",
      background: "bg-slate-100",
      text: "bg-slate-500 text-white",
    },
    option19: {
      foreground: "text-zinc-500",
      background: "bg-zinc-100",
      text: "bg-zinc-500 text-white",
    },
    option20: {
      foreground: "text-neutral-500",
      background: "bg-neutral-100",
      text: "bg-neutral-500 text-white",
    },
  },
  icons: {
    option1: BadgeDollarSign,
    option2: PiggyBank,
    option3: Wallet,
    option4: TrendingUp,
    option5: CreditCard,
    option6: Landmark,
    option7: Receipt,
    option8: Target,
    option9: ArrowUpCircle,
    option10: ArrowDownCircle,
    option11: Calculator,
    option12: ChartBar,
    option13: Coins,
    option14: DollarSign,
    option15: HandCoins,
    option16: Banknote,
    option17: CircleDollarSign,
    option18: LineChart,
    option19: WalletCards,
    option20: Percent,
  },
  gradients: {
    option1: "from-blue-500 to-green-500",
    option2: "from-purple-500 to-pink-500",
    option3: "from-yellow-500 to-red-500",
    option4: "from-green-500 to-blue-500",
    option5: "from-indigo-500 to-purple-500",
    option6: "from-pink-500 to-rose-500",
    option7: "from-cyan-500 to-blue-500",
    option8: "from-teal-500 to-green-500",
    option9: "from-orange-500 to-red-500",
    option10: "from-emerald-500 to-teal-500",
    option11: "from-violet-500 to-purple-500",
    option12: "from-amber-500 to-orange-500",
    option13: "from-lime-500 to-green-500",
    option14: "from-fuchsia-500 to-pink-500",
    option15: "from-sky-500 to-blue-500",
    option16: "from-rose-500 to-pink-500",
    option17: "from-blue-500 to-purple-500",
    option18: "from-green-500 to-emerald-500",
    option19: "from-red-500 to-orange-500",
    option20: "from-purple-500 to-blue-500",
  },
}